
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    basedir: /tmp/tomcat
    connection-timeout: 60000

spring:
  application:
    name: demo-gateway
    cloud:
      gateway:
        routes:

eureka:
  instance:
    hostname: gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka/


